## Get all
GET http://localhost:3001/api/notes

###delete
DELETE http://localhost:3001/api/notes/3


### POST
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "sup!",
    "important": false
}

### PUT
PUT http://localhost:3001/api/notes/682e8bd2e4d1a648c7024d2b
Content-Type: application/json

{
    "content": "This is updating!",
    "important": true
}